#!/bin/bash

PREFIX='ssh'
source "config"
source "${LIB}/log"
source "${LIB}/installed"
source "${LIB}/repeat"

cd ${PKG}/ssh

RequireInstall

if [ "$1" != '-v' ]; then
	USER="$1"
else
	USER=''
fi

USERS=$(ls ${SSH_KEYS})
VERBOSE=false
SPACE="          "
DASHES=50

for ARG in "$@"; do
    if [ "${ARG}" = "-v" ]; then
    	VERBOSE=true
    fi
done

function ExtractKeys
{
	local FILE KEYS ROW
	FILE=$1

	KEYS=$(sed -n "/${SSH_CONFIG_BANNER_START}/,/${SSH_CONFIG_BANNER_END}/p" ${FILE})
	KEYS=$(echo "${KEYS}" | sed '/^$/d') # remove empty lines
	KEYS=$(echo "${KEYS}" | grep -v "${SSH_CONFIG_BANNER_START}" | grep -v "${SSH_CONFIG_BANNER_END}")

	if [ -z "${KEYS}" ]; then
		LogBrown "No keys found"
		return
	fi

	KEYS=$(echo "${KEYS}" | grep -v '# Key ')

	i=1
	while read -r ROW; do
		if [ "$(echo ${ROW} | head -c 1)" = "#" ]; then
			Log "$i) $(echo "${ROW}" | sed 's/^# //')"
			((i++))
		elif $VERBOSE; then
			echo "${ROW}"
		fi
	done <<< "${KEYS}"
}

# For all users
if [ -z "${USER}" ]; then
	Log "List of keys for all users"
	Log $(Repeat "-" ${DASHES})
	for USR in ${USERS}; do
		Log "User: ${USR}"
		ExtractKeys "${SSH_KEYS}/${USR}/${SSH_FILE}"
		Log $(Repeat "-" ${DASHES})
	done
	exit
fi

# For specific user
if [ ! -f "${SSH_KEYS}/${USER}/${SSH_FILE}" ]; then
	LogBrown "No configuration found for user ${USER}"
	exit
fi

Log "List of keys for user"
Log "User: ${USER}"
Log $(Repeat "-" ${DASHES})
ExtractKeys "${SSH_KEYS}/${USER}/${SSH_FILE}"
Log $(Repeat "-" ${DASHES})