#!/bin/bash

################
# Command name #
################
# If you change this value the commands will be called with the new name
# eg: if CMDNAME="commands"
# istead of "tools nginx site"
# it will be "commands nginx site"
#
# Note: if you change the name after the installation
# the change will not take effect

CMDNAME="tools"


BINDIR="/usr/local/bin"
INSTALLDIR="/usr/local/lib"

####################
# Main directories #
####################

TOOLS="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
CMD="${TOOLS}/cmd"
LIB="${TOOLS}/lib"
SRC="${TOOLS}/src"

####################
# Commands configs #
####################

USERNAME=`who am i | awk '{print $1}'`

# apache && nginx
WEBDIR="/srv/www"
WEBDIR_PUBLIC="www/public"
GITDIR="/srv/git"

# mail
MAILDIR="/srv/mail"
MAILUSER="vmail"

# ftp
FTPUSER="ftp"

# ssh
SSH_KEYS="/etc/ssh/keys"
SSH_FILE="authorized_keys"
SSH_CONFIG_BANNER_START="# TOOLS AUTOMATIC MANAGEMENT START"
SSH_CONFIG_BANNER_END="# TOOLS AUTOMATIC MANAGEMENT END"
SSH_KEY_BANNER_START="# Key start"
SSH_KEY_BANNER_END="# Key end"