#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
	DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
	SOURCE="$(readlink "$SOURCE")"
	[[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done

CMDNAME="tools"

# Main directories
TOOLS="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
CMD="${TOOLS}/cmd"
LIB="${TOOLS}/lib"
SRC="${TOOLS}/src"

# Commands configs

USERNAME=`who am i | awk '{print $1}'`

BINDIR="/usr/local/bin"
INSTALLDIR="/usr/local/lib"

WEBDIR="/srv/www"
WEBDIR_PUBLIC="www/public"

GITDIR="/srv/git"

MAILDIR="/srv/mail"
MAILUSER="vmail"

FTPUSER="ftp"

SSH_KEYS="/etc/ssh/keys"
SSH_FILE="authorized_keys"
SSH_CONFIG_BANNER_START="# TOOLS AUTOMATIC MANAGEMENT START"
SSH_CONFIG_BANNER_END="# TOOLS AUTOMATIC MANAGEMENT END"
SSH_KEY_BANNER_START="# Key start"
SSH_KEY_BANNER_END="# Key end"