#!/bin/bash

if [ -z "$SUDO_COMMAND" ]; then
	mntusr=$(id -u) grpusr=$(id -g) sudo $0 "$@"
	exit 0
fi

PREFIX='tools'
DIR=$(dirname "$(readlink -f "$0")")

source "${DIR}/config"
source "${LIB}/log"

Log "Installing ..."

if [ ! -d "${BINDIR}" ]; then
	LogBrown "${BINDIR} does not exists. Attempt to create it"

	if [ ! $(mkdir ${BINDIR} 2> /dev/null) ]; then
		LogRed "Could not create ${BINDIR}"
		exit
	fi

	Log "Changing owner of ${BINDIR} to ${USERNAME}"
	sudo chown "${USERNAME}" "${BINDIR}"
fi

if [ ! -w "${BINDIR}" ]; then
	LogRed "${BINDIR} is not writable by you"
	exit
fi

if [ -h "${BINDIR}/${CMDNAME}" ]; then
	LogBrown "Symbolic link already exists: ${BINDIR}/${CMDNAME}"
else
	Log "Creating symlink ${BINDIR}/${CMDNAME}"
	ln -s ${DIR}/${CMDNAME} ${BINDIR}/${CMDNAME}
fi

Log "Installing bash completion"
if [ ! -f "/etc/bash_completion.d/${CMDNAME}" ]; then
    ln -s "${TOOLS}/tools_completion" /etc/bash_completion.d/tools
else
	LogBrown "Bash completion already exists"
fi

LogGreen "Installation was successful!"
LogBlue "Reopen terminal to activate bash completion"