#!/bin/bash

clear

if [ -z "$SUDO_COMMAND" ]; then
	mntusr=$(id -u) grpusr=$(id -g) sudo $0 $*
	exit 0
fi

PREFIX='tools'
DIR=$(dirname "$(readlink -f "$0")")

source "${DIR}/config"
source "${LIB}/log"

Log "Installing ..."

if [ ! -d "${BINDIR}" ]; then
	LogBrown "${BINDIR} does not exists. Attempt to create it"

	if [ ! $(mkdir ${BINDIR} 2> /dev/null) ]; then
		LogRed "Could not create ${BINDIR}"
		exit
	fi

	Log "Changing owner of ${BINDIR} to ${USERNAME}"
	sudo chown "${USERNAME}" "${BINDIR}"
fi

if [ ! -w "${BINDIR}" ]; then
	LogRed "${BINDIR} is not writable by you"
	exit
fi

if [ -h "${BINDIR}/${CMDNAME}" ]; then
	LogBrown "Symbolic link already exists: ${BINDIR}/${CMDNAME}"
else
	Log "Creating symlink ${BINDIR}/${CMDNAME}"
	ln -s ${DIR}/${CMDNAME} ${BINDIR}/${CMDNAME}
fi

Log "Installing bash completion"
if [ ! -f "/etc/bash_completion.d/${CMDNAME}" ]; then
cat >> "/etc/bash_completion.d/${CMDNAME}" <<EOF
_tools()
{
    local CURCMD PREVCMD COMMANDS DIR CMD PARAMS
    COMPREPLY=()
    CURCMD="\${COMP_WORDS[COMP_CWORD]}"
    PREVCMD="\${COMP_WORDS[COMP_CWORD-1]}"

    DIR=\$(dirname "\$(readlink -f /usr/local/bin/tools)")

    COMMANDS=\$(find "\${DIR}/cmd/" -maxdepth 1 -type d -not -path "\${DIR}/cmd/" -exec basename {} \;)

    if [ ! -z "\${PREVCMD}" ]; then
        for CMD in \${COMMANDS}; do
            if [ "\${CMD}" != "\${PREVCMD}" ]; then
                continue
            fi

            PARAMS=\$(find "\${DIR}/cmd/\${CMD}/" -maxdepth 1 -type f -not -path "\${DIR}/cmd/\${CMD}/" -exec basename {} \;)
            COMPREPLY=( \$(compgen -W "\${PARAMS}" -- \${CURCMD}) )
            return 0
        done
    fi

    COMPREPLY=(\$(compgen -W "\${COMMANDS}" -- \${CURCMD}))
    return 0
}
complete -F _tools tools
EOF
else
	LogBrown "Bash completion already exists"
fi

LogGreen "Installation was successful!"
LogBlue "Reopen terminal to activate bash completion"