#!/bin/bash

# Used for remote setup
# one line command for install

if [ -z "$SUDO_COMMAND" ]; then
	echo 'Run as: sudo bash <(curl -sL http://git.io/vmrmO)'
	exit 0
fi

apt-get install -y git
cd /srv
git clone https://github.com/IvanDokov/tools
cd tools
./install