#!/bin/bash

if [ -z "$SUDO_COMMAND" ]; then
	mntusr=$(id -u) grpusr=$(id -g) sudo $0 "$@"
	exit 0
fi

PREFIX='tools'

DIR=$(dirname "$(readlink -f "$0")")
cd "${DIR}"

source "config"
source "lib/log"

if [ ! -h "${BINDIR}/${CMDNAME}" ]; then
	LogRed "${CMDNAME} is not installed! Run ./install"
	exit
fi

function Join { local IFS="$1"; shift; echo -n "$*"; }

function ShowHelp {
	local SELECTEDCMD="$1"

	cd ${PKG}

	COMMANDS=$(find . -maxdepth 1 -type d -not -path "." -exec basename {} \;)

	for CM in ${COMMANDS}; do
		if [ ! -z "${SELECTEDCMD}" ]; then
			if [ "${CM}" != "${SELECTEDCMD}" ]; then
				continue
			fi
		fi

		Log "${CM}" true

		PARAMS=$(find ${CM} -maxdepth 1 -type f -not -path "." -exec basename {} \;)
		if [ ${#PARAMS} -gt 0 ]; then
			echo -n " ["; Join "|" ${PARAMS}; echo -n "]"
		fi
		echo ""
		Log ""
	done
}

if [ -z "$1" ]; then
	LogBrown "Available packages and their arguments:"
	Log ""
	ShowHelp
	exit
fi

if [ ! -d "${PKG}/$1" ]; then
	LogBrown "Package not found: $1"
	Log ""
	ShowHelp
	exit
fi

if [ ! -f "${PKG}/$1/$2" ]; then
	LogBrown "Package argument is invalid: $2"
	Log ""
	ShowHelp $1
	exit
fi

# Invoke command

sudo bash "${PKG}/$1/$2" "${@:3}"