#!/bin/bash

if [ -z "$SUDO_COMMAND" ]; then
	mntusr=$(id -u) grpusr=$(id -g) sudo $0 "$@"
	exit 0
fi

PREFIX='tools'

DIR=$(dirname "$(readlink -f "$0")")
cd "${DIR}"

source "config"
source "lib/log"
source "lib/pkgs"

if [ ! -h "${BINDIR}/${CMDNAME}" ]; then
	LogRed "${CMDNAME} is not installed! Run ./install"
	exit
fi

function Join { local IFS="$1"; shift; echo -n "$*"; }

function ShowHelp {
	local SELECTEDCMD="$1"

	GetInstalled
	GetNotInstalled

	if [ -z "${SELECTEDCMD}" ]; then
		if [ ${#INSTALLED} -gt 0 ]; then
			LogBrown "Installed packages:"
			for CM in ${INSTALLED[@]}; do
				Log "${CM}"
			done
			Log
		fi

		if [ ${#NOTINSTALLED} -gt 0 ]; then
			LogBrown "Not installed packages:"
			for CM in ${NOTINSTALLED[@]}; do
				Log "${CM}"
			done
			Log
		fi
	else
		GetParams "${SELECTEDCMD}"

		Log "" true

		for PARAM in ${PARAMS}; do
			echo -n "${PARAM}   "
		done

		echo ""
		Log
	fi
}

if [ -z "$1" ]; then
	ShowHelp
	exit
fi

if [ ! -d "${PKG}/$1" ]; then
	LogRed "Package not found: $1"
	Log
	ShowHelp
	exit
fi

if [ ! -f "${PKG}/$1/$2" ]; then
	LogRed "Package argument is invalid: $2"
	Log
	LogBrown "Available arguments:"
	ShowHelp $1
	exit
fi

# Invoke command

sudo bash "${PKG}/$1/$2" "${@:3}"