#!/bin/bash

PREFIX='nginx'
source "config"
source "${LIB}/log"
source "${LIB}/installed"

cd ${PKG}/nginx

ProtectDoubleInstall

MYSQL=false

if ! type mysql >/dev/null 2>&1; then
	Log 'Do you want to install MySQL [Y/n]: ' true
	read YN_MYSQL

	case $YN_MYSQL in
		[nN] | [n|N][O|o] );;
		*)
			MYSQL=true
			while true; do
				Log "MySQL root password: " true
				read -s MYSQL_ROOT_PASS
				echo ""

				if [ ! -z "${MYSQL_ROOT_PASS}" ]; then
					break
				fi
			done
			;;
	esac
fi

Log "Adding ppa for nginx stable"
apt-add-repository ppa:nginx/stable -y 2&>1 > /dev/null

Log "Adding ppa for php 5.6"
apt-add-repository ppa:ondrej/php5-5.6 -y 2&>1 > /dev/null

Log "Updating software repositories"
apt-get update > /dev/null

Log "Installing nginx"
apt-get install -y -q nginx php5-fpm php5-mysql php5-curl php5-mcrypt php5-cli php5-gd php5-intl > /dev/null

Log "Restarting nginx"
service nginx restart > /dev/null

Log "Configuring php5-fpm"
sed -i 's/upload_max_filesize = .*/upload_max_filesize = 10M/' /etc/php5/fpm/php.ini
php5enmod mcrypt

Log "Restarting php5-fpm"
service php5-fpm restart > /dev/null

if [ ${MYSQL} == true ]; then
	Log "Installing MySQL"

	sudo debconf-set-selections <<< "mysql-server mysql-server/root_password password ${MYSQL_ROOT_PASS}"
	sudo debconf-set-selections <<< "mysql-server mysql-server/root_password_again password ${MYSQL_ROOT_PASS}"
	apt-get install -y mysql-server > /dev/null

	LogGreen "MySQL installed successfully"
	LogBrown "Suggestion: secure the database with mysql_secure_installation"
fi

Log "Installing Composer"
curl -sS https://getcomposer.org/installer | php
mv composer.phar /usr/local/bin/composer

Log "Installing git"
apt-get install -y -q git > /dev/null

Log "Installing Postfix"
debconf-set-selections <<< "postfix postfix/mailname string $(hostname)"
debconf-set-selections <<< "postfix postfix/main_mailer_type string 'Internet Site'"
apt-get install -y -q postfix > /dev/null

MarkInstalled

echo ""
LogGreen "Installed successfully"
echo ""

debconf-set-selections <<< "postfix postfix/mailname string $(hostname)"
debconf-set-selections <<< "postfix postfix/main_mailer_type string 'Internet Site'"
apt-get install -y postfix
