#!/bin/bash

PREFIX='apache'
source "config"
source "${LIB}/log"
source "${LIB}/installed"

cd ${PKG}/apache

ProtectDoubleInstall

MYSQL=false

if ! type mysql >/dev/null 2>&1; then
	Log 'Do you want to install MySQL [Y/n]: ' true
	read YN_MYSQL

	case $YN_MYSQL in
		[nN] | [n|N][O|o] );;
		*)
			MYSQL=true
			while true; do
				Log "MySQL root password: " true
				read -s MYSQL_ROOT_PASS
				echo ""

				if [ ! -z "${MYSQL_ROOT_PASS}" ]; then
					break
				fi
			done
			;;
	esac
fi

Log "Checking for multiverse repositories"
if ! grep 'deb http://archive.ubuntu.com/ubuntu' /etc/apt/sources.list | grep -v '#' | grep -q 'multiverse'; then
	echo "deb http://archive.ubuntu.com/ubuntu trusty multiverse" >> /etc/apt/sources.list;
	Log "Added deb http://archive.ubuntu.com/ubuntu trusty multiverse"
fi
if ! grep 'deb http://archive.ubuntu.com/ubuntu trusty-updates multiverse' /etc/apt/sources.list | grep -v '#' | grep -q 'multiverse'; then
	echo "deb http://archive.ubuntu.com/ubuntu trusty-updates multiverse" >> /etc/apt/sources.list;
	Log "Added deb http://archive.ubuntu.com/ubuntu trusty-updates multiverse"
fi
if ! grep 'deb http://security.ubuntu.com/ubuntu trusty-security multiverse' /etc/apt/sources.list | grep -v '#' | grep -q 'multiverse'; then
	echo "deb http://security.ubuntu.com/ubuntu trusty-security multiverse" >> /etc/apt/sources.list;
	Log "Added deb http://security.ubuntu.com/ubuntu trusty-security multiverse"
fi

Log "Updating software repositories"
apt-get update > /dev/null

Log "Installing Apache2"
apt-get install -y -q apache2 libapache2-mod-fastcgi php5-fpm php5-mysql php5-curl php5-mcrypt php5-cli php5-gd php5-intl > /dev/null

if ! cat /etc/apache2/apache2.conf | grep -q 'ServerName'; then
	echo "ServerName localhost" >> /etc/apache2/apache2.conf
fi

Log "Enabling modules"
a2enmod actions fastcgi alias rewrite include expires headers > /dev/null

Log "Configuring Apache2"
cat > /etc/apache2/conf-available/php5-fpm.conf <<EOF
<IfModule mod_fastcgi.c>
	<Directory /usr/lib/cgi-bin>
		Require all granted
	</Directory>
</IfModule>
EOF
a2enconf php5-fpm.conf > /dev/null

Log "Restarting Apache2"
service apache2 restart > /dev/null

Log "Configuring php5-fpm"
sed -i 's/upload_max_filesize = .*/upload_max_filesize = 10M/' /etc/php5/fpm/php.ini
php5enmod mcrypt

Log "Restarting php5-fpm"
service php5-fpm restart > /dev/null

if [ ${MYSQL} == true ]; then
	Log "Installing MySQL"

	sudo debconf-set-selections <<< "mysql-server mysql-server/root_password password ${MYSQL_ROOT_PASS}"
	sudo debconf-set-selections <<< "mysql-server mysql-server/root_password_again password ${MYSQL_ROOT_PASS}"
	apt-get install -y mysql-server > /dev/null

	LogGreen "MySQL installed successfully"
	LogBrown "Suggestion: secure the database with mysql_secure_installation"
fi

Log "Installing Composer"
curl -sS https://getcomposer.org/installer | php
mv composer.phar /usr/local/bin/composer

Log "Installing git"
apt-get install -y -q git > /dev/null

Log "Installing Postfix"
debconf-set-selections <<< "postfix postfix/mailname string $(hostname)"
debconf-set-selections <<< "postfix postfix/main_mailer_type string 'Internet Site'"
apt-get install -y -q postfix > /dev/null

MarkInstalled

echo ""
LogGreen "Installed successfully"
echo ""