#!/bin/bash

clear

if [ -z "$SUDO_COMMAND" ]; then
	mntusr=$(id -u) grpusr=$(id -g) sudo $0 $*
	exit 0
fi

PREFIX='apache'
source "$(dirname $(dirname $(dirname "$(readlink -f "$0")")))/config"
source "${LIB}/log"

MYSQL=false

if ! type mysql >/dev/null 2>&1; then
	Log 'Do you want to install MySQL [Y/n]: ' true
	read YN_MYSQL

	case $YN_MYSQL in
		[nN] | [n|N][O|o] );;
		*)
			MYSQL=true
			while true; do
				Log "MySQL root password: " true
				read -s MYSQL_ROOT_PASS
				echo ""

				if [ ! -z "${MYSQL_ROOT_PASS}" ]; then
					break
				fi
			done
			;;
	esac
fi

Log "Updating software repositories"
apt-get update > /dev/null

Log "Installing web server"
apt-get install -y -q apache2 libapache2-mod-fastcgi php5-fpm php5-mysql php5-curl php5-mcrypt php5-cli php5-gd php5-intl > /dev/null

if ! cat /etc/apache2/apache2.conf | grep -q 'ServerName'; then
	echo "ServerName localhost" >> /etc/apache2/apache2.conf
fi

Log "Enabling modules"
a2enmod actions fastcgi alias rewrite include expires headers > /dev/null

Log "Configuring Apache2"
cat > /etc/apache2/conf-available/php5-fpm.conf <<EOF
<IfModule mod_fastcgi.c>
	<Directory /usr/lib/cgi-bin>
		Require all granted
	</Directory>
</IfModule>
EOF
a2enconf php5-fpm.conf > /dev/null

Log "Restarting Apache2"
service apache2 restart > /dev/null

Log "Configuring php5-fpm"
sed -i 's/upload_max_filesize = .*/upload_max_filesize = 10M/' /etc/php5/fpm/php.ini

Log "Restarting php5-fpm"
service php5-fpm restart > /dev/null

if [ ${MYSQL} == true ]; then
	Log "Installing MySQL"

	sudo debconf-set-selections <<< "mysql-server mysql-server/root_password password ${MYSQL_ROOT_PASS}"
	sudo debconf-set-selections <<< "mysql-server mysql-server/root_password_again password ${MYSQL_ROOT_PASS}"
	apt-get install -y mysql-server > /dev/null

	LogGreen "MySQL installed successfully"
	LogBrown "Suggestion: secure the database with mysql_secure_installation"
fi

Log "Installing git"
apt-get install -y -q git > /dev/null

Log "Installing sendmail"
apt-get install -y -q sendmail > /dev/null

LogGreen "Installed successfully"