#!/bin/bash

PREFIX='mail'
source "config"
source "${LIB}/log"
source "${LIB}/installed"
source "${PKG}/mail/tmp/mysql"
source "${PKG}/mail/lib/validate"
source "${PKG}/mail/lib/functions"

cd ${PKG}/mail

RequireInstall

if [ -z "${SOURCE}" ]; then
	while true; do
		Log "Source: " true
		read SOURCE

		if [ ! -z "${SOURCE}" ]; then
			break
		fi
	done
fi
if [ -z "${DESTINATION}" ]; then
	while true; do
		Log "Destination: " true
		read DESTINATION

		if [ ! -z "${DESTINATION}" ]; then
			break
		fi
	done
fi

Query "INSERT INTO ${MAIL_MYSQL_DATABASE}.aliases (\`source\`, \`destination\`) VALUES ('${SOURCE}', '${DESTINATION}')"
SOURCE=
DESTINATION=