#!/bin/bash

PREFIX='mail'
source "config"
source "${LIB}/log"
source "${LIB}/installed"
source "${PKG}/mail/tmp/mysql"
source "${PKG}/mail/lib/validate"
source "${PKG}/mail/lib/functions"

cd ${PKG}/mail

RequireInstall

List
if [ -z "${ID}" ]; then
	while true; do
		Log "Edit row ID: " true
		read ID

		if [ ! -z "${ID}" ]; then
			break
		fi
	done
fi

List ${ID}
Log "Are you sure you want to delete this alias [y/n]: " true
read YN

if [ $(echo $YN | awk '{print tolower($0)}') = "y" ]; then
	Query "DELETE FROM ${MAIL_MYSQL_DATABASE}.aliases WHERE id = '${ID}'"
fi