#!/bin/bash

PREFIX='mail'
source "config"
source "${LIB}/log"
source "${LIB}/installed"
source "${PKG}/mail/tmp/mysql"
source "${PKG}/mail/lib/validate"
source "${PKG}/mail/lib/functions"

cd ${PKG}/mail

RequireInstall

GetUserAndDomain "$1"

EMAIL_DATA=$(Query "SELECT emails.id, emails.user, domains.domain, emails.active, emails.name FROM ${MAIL_MYSQL_DATABASE}.emails LEFT JOIN ${MAIL_MYSQL_DATABASE}.domains ON emails.domain_id = domains.id WHERE emails.user = '${USER}' AND domains.domain = '${DOMAIN}'")

if [ -z "${EMAIL_DATA}" ]; then
	LogRed "Email not found!"
	exit
fi

ID=$(echo "${EMAIL_DATA}" | awk '{print $1}')
NAME=$(echo "${EMAIL_DATA}" | awk '{for(i=5;i<=NF;++i)printf "%s ",$i}')

Log "Name: " true
read NAME_NEW
if [ ! -z "${NAME_NEW}" ]; then
	AppendToUpdate "name = '${NAME_NEW}'"
fi

if [ ! -z "${UPDATE}" ]; then
	UPDATE="UPDATE ${MAIL_MYSQL_DATABASE}.emails SET ${UPDATE} WHERE id = ${ID}"
	Query "${UPDATE}"
	LogGreen "Successfully updated"
else
	LogBrown "Nothing changed"
fi