#!/bin/bash

PREFIX='mail'
source "config"
source "${LIB}/log"
source "${LIB}/installed"
source "${PKG}/mail/tmp/mysql"
source "${PKG}/mail/lib/validate"
source "${PKG}/mail/lib/functions"

cd ${PKG}/mail

RequireInstall

EMAIL="$1"

GetUserAndDomain

if [ -z "${EMAIL}" ]; then
	while true; do
		Log "Email: " true
		read EMAIL

		GetUserAndDomain

		if [ -z "$DOMAIN" ]; then
			LogBrown "Email format is invalid. Missing @"
		else
			break
		fi
	done
fi

EMAIL_DATA=$(Query "SELECT emails.id, emails.user, domains.domain, emails.active, emails.name FROM ${MAIL_MYSQL_DATABASE}.emails LEFT JOIN ${MAIL_MYSQL_DATABASE}.domains ON emails.domain_id = domains.id WHERE emails.user = '${USER}' AND domains.domain = '${DOMAIN}'")

if [ -z "${EMAIL_DATA}" ]; then
	LogRed "Email not found!"
	exit
fi

ID=$(echo "${EMAIL_DATA}" | awk '{print $1}')
ACTIVE=$(echo "${EMAIL_DATA}" | awk '{print $4}')

AppendToUpdate "active = 0"

UPDATE="UPDATE ${MAIL_MYSQL_DATABASE}.emails SET ${UPDATE} WHERE id = ${ID}"
Query "${UPDATE}"
LogGreen "Successfully deactivated"