#!/bin/bash

function ProtectDoubleInstall {
    if [ -f "${INSTALLEDCACHE}" ]; then
        LogRed "Already installed!"
        exit
    fi
}

function RequireInstall {
	if [ ! -f "${INSTALLEDCACHE}" ]; then
		LogRed "This software is not installed"
		exit
	fi
}

function MarkInstalled {
    if [ ! -d "tmp" ]; then
        mkdir "tmp"
    fi
    touch "${INSTALLEDCACHE}"
}

function MarkUninstalled {
    if [ -f "${INSTALLEDCACHE}" ]; then
    	rm "${INSTALLEDCACHE}"
    fi
}