#!/bin/bash

function ProtectDoubleInstall {
    if [ -f "tmp/installed" ]; then
        LogRed "Already installed!"
        exit
    fi
}

function RequireInstall {
	if [ ! -f "tmp/installed" ]; then
		LogRed "This software is not installed"
		exit
	fi
}

function MarkInstalled {
    if [ ! -d "tmp" ]; then
        mkdir "tmp"
    fi
    touch "tmp/installed"
}

function MarkUninstalled {
    if [ -f "tmp/installed" ]; then
    	rm "tmp/installed"
    fi
}