#!/bin/bash

function GetCommands {
    COMMANDS=$(find "${PKG}" -maxdepth 1 -type d -not -path "${PKG}" -exec basename {} \;)
}

function GetInstalled {
    GetCommands

    INSTALLED=()
    for CM in ${COMMANDS}; do
        if [ ! -f "${PKG}/${CM}/${INSTALLEDCACHE}" ]; then continue; fi
        INSTALLED+=(${CM})
    done
}

function GetNotInstalled {
    GetCommands

    NOTINSTALLED=()
    for CM in ${COMMANDS}; do
        if [ -f "${PKG}/${CM}/${INSTALLEDCACHE}" ]; then continue; fi
        NOTINSTALLED+=(${CM})
    done
}

function GetParams {
    local CMD
    CMD="$1"

    PARAMS=$(find "${PKG}/${CMD}" -maxdepth 1 -type f -not -path "." -exec basename {} \;)

    if [ ! -f "${PKG}/${CMD}/${INSTALLEDCACHE}" ] && [ -f "${PKG}/${CMD}/install" ]; then
        PARAMS=('install')
    else
        DELETE=('install')
        PARAMS=("${PARAMS[@]/$DELETE}")
    fi
}