#!/bin/bash

if [ -z "$SUDO_COMMAND" ]; then
    mntusr=$(id -u) grpusr=$(id -g) sudo $0 $*
    exit 0
fi

clear

PREFIX='ssh'
source "$(dirname $(dirname $(dirname "$(readlink -f "$0")")))/config"
source "${LIB}/log"

cd ${CMD}/ssh

CheckIfInstalled



MarkInstalled

echo ""
LogGreen "Installed successfully"
echo ""