#!/bin/bash

while read oldrev newrev ref
do
	CNF="/src/tools/config"
	if [ -f "${CNF}" ]; then
		source ${CNF}
	else
		WEBDIR="/srv/www"
	fi

	SITE=$(basename $(pwd))
	SITE_DIR="${WEBDIR}/${SITE}/www"

	BRANCH=$(echo $ref | cut -d/ -f3)

	G=$(echo -e "\033[0;36m")
	P=$(echo -e "\033[0;35m")
	N=$(echo -e "\033[0m")

	if [ ! -d "${SITE_DIR}" ]; then
		exit;
	fi

	if [ "deploy" == "${BRANCH}" ]; then
		GIT_WORK_TREE="${SITE_DIR}" git checkout -qf "${BRANCH}" 2>&1 >/dev/null
		echo -e "${G}Website${N} ${P}${SITE}${N} ${G}updated by ${BRANCH}${N}"
	fi
done