#!/bin/bash

PREFIX='ftp'
source "config"
source "${LIB}/log"
source "${LIB}/installed"
source "${CMD}/ftp/tmp/mysql"
source "${CMD}/ftp/lib/validate"

cd ${CMD}/ftp

RequireInstall

USER="$1"

GetUser

ValidateUser

Query "UPDATE ${FTP_MYSQL_DATABASE}.accounts SET Status = '1' WHERE User = '${USER}'"

LogGreen "Activated"