#!/bin/bash

PREFIX='ftp'
source "config"
source "${LIB}/log"
source "${LIB}/installed"
source "${CMD}/ftp/tmp/mysql"
source "${CMD}/ftp/lib/validate"
source "${CMD}/ftp/lib/functions"

cd ${CMD}/ftp

RequireInstall

USER="$1"

GetUser

ValidateUser

while true; do
	Log "Password: " true
	read -s PASS_NEW && echo ""
	if [ ! -z "${PASS_NEW}" ]; then
		break
	fi
done

Query "UPDATE ${FTP_MYSQL_DATABASE}.accounts SET password = md5('${PASS_NEW}') WHERE User = '${USER}'"

LogGreen "Password changed successfully"