#!/bin/bash

function Query {
    MYSQL_PWD=${MAIL_MYSQL_PASSWORD} mysql -u${MAIL_MYSQL_USERNAME} -s -e "$1"
}

function List {
	if [ -z "$1" ]; then
		Query "SELECT * FROM ${MAIL_MYSQL_DATABASE}.aliases"
	else
		Query "SELECT * FROM ${MAIL_MYSQL_DATABASE}.aliases WHERE id = '$1'"
	fi
}

function GetUserAndDomain {
	USER=$(echo "${EMAIL}" | awk -F\@ '{print $1}')
	DOMAIN=$(echo "${EMAIL}" | awk -F\@ '{print $2}')
}

UPDATE=""
function AppendToUpdate {
	if [ -z "${UPDATE}" ]; then
		UPDATE="$1"
	else
		UPDATE="${UPDATE}, $1"
	fi
}