#!/bin/bash

PREFIX='bash'
source "config"
source "${LIB}/log"

Log "Installing bash_profile"

BASH_PROFILE_TARGET="source ${CMD}/bash/src/bash_profile"
LOCAL_PROFILE="~/.bash_profile"
ROOT_PROFILE="/root/.bash_profile"

if [ "${USERNAME}" != "root" ]; then
	if ! grep -q "${BASH_PROFILE_TARGET}" /home/${USERNAME}/.bash_profile 2> /dev/null; then
		echo "${BASH_PROFILE_TARGET}" >> /home/${USERNAME}/.bash_profile
		chown ${USERNAME}:${USERNAME} /home/${USERNAME}/.bash_profile
	fi
fi

if ! grep -q "${BASH_PROFILE_TARGET}" /root/.bash_profile 2> /dev/null; then
	echo "${BASH_PROFILE_TARGET}" >> /root/.bash_profile
	chown root:root /root/.bash_profile
fi

if ! grep -q 'source /root/.bash_profile' /root/.bashrc 2> /dev/null; then
	echo 'source /root/.bash_profile' > /root/.bashrc
fi

LogGreen "Successfully installed"
Log "Reopen terminal or use this command:"
LogBlue "source ~/.bash_profile"