#!/bin/bash

PREFIX='ftp'
source "config"
source "${LIB}/log"
source "${LIB}/installed"
source "${PKG}/ftp/tmp/mysql"
source "${PKG}/ftp/lib/validate"

cd ${PKG}/ftp

RequireInstall

while true; do
	Log "Username: " true
	read FTP_USERNAME

	if [ ! -z "${FTP_USERNAME}" ]; then
		break
	fi
done

while true; do
	Log "Password: " true
	read -s FTP_PASSWORD

	if [ ! -z "${FTP_PASSWORD}" ]; then
		echo ""
		break
	fi
	echo ""
done

while true; do
	Log "Home path [/home/${FTP_USERNAME}]: " true
	read CHROOTPATH

	if [ -z "${CHROOTPATH}" ]; then
		CHROOTPATH="/home/${FTP_USERNAME}"
	fi

	if [ -d "${CHROOTPATH}" ]; then
		LogBrown "${CHROOTPATH} already exists! Are you sure? [y/n]: " true
		read YN_DIR

		case $YN_DIR in
			[yY] | [y|Y][E|e][S|s] )
				break
				;;
		esac
	else
		mkdir -p "${CHROOTPATH}"

		break
	fi
done

while true; do
	Log "System user [${FTPUSER}]: " true
	read SYS_USER

	if [ ! -z "${SYS_USER}" ]; then
		SYS_UID=$(id -u ${SYS_USER} 2>&1)
		if echo "${SYS_UID}" | grep -q 'no such user'; then
			LogBrown "No such user found"
		else
			SYS_GID=$(id -g ${SYS_USER} 2>&1)
			if echo "${SYS_GID}" | grep -q 'no such user'; then
				SYS_GID=2001
			fi
			break
		fi
	else
		SYS_USER="${FTPUSER}"
		SYS_UID=2001
		SYS_GID=2001
		break
	fi
done

chown "${SYS_USER}":"${SYS_USER}" "${CHROOTPATH}"
chmod 750 "${CHROOTPATH}"

QUERY="INSERT INTO \`${FTP_MYSQL_DATABASE}\`.\`accounts\` (\`User\`, \`Status\`, \`Password\`, \`IPAccess\`, \`Dir\`, \`Uid\`, \`Gid\`, \`ULBandwidth\`, \`DLBandwidth\`, \`QuotaSize\`, \`QuotaFiles\`) VALUES ('${FTP_USERNAME}', '1', MD5('${FTP_PASSWORD}'), '*', '${CHROOTPATH}', '${SYS_UID}', '${SYS_GID}', '0', '0', '0', '0');"

RESULT=`MYSQL_PWD=${FTP_MYSQL_PASSWORD} mysql -u ${FTP_MYSQL_USERNAME} -e "${QUERY}" 2>&1`

if echo "${RESULT}" | grep -q "Duplicate entry '${FTP_USERNAME}'"; then
	LogRed "This account already exists"
else
	LogGreen "FTP user created: ${FTP_USERNAME}"
fi