#!/bin/bash

clear

if [ -z "$SUDO_COMMAND" ]; then
	mntusr=$(id -u) grpusr=$(id -g) sudo $0 $*
	exit 0
fi

PREFIX='teamspeak'
source "$(dirname "$(readlink -f "$0")")/lib/log"
source "$(dirname "$(readlink -f "$0")")/config"

cd ${CMD}/teamspeak

Log "Installing TeamSpeak 3 server to ${INSTALLDIR}/ts"
if [ -n "`uname -m | grep 64`" ]; then
    cp -R x64 ${INSTALLDIR}/ts
else
    cp -R x86 ${INSTALLDIR}/ts
fi

Log "Creating TeamSpeak 3 user: ts"
useradd -M -p! ts

Log "Setting up permissions for user ts"
chown -R ts:ts ${INSTALLDIR}/ts

Log "Creating startup script"
cat > /etc/init.d/ts <<EOF
#! /bin/sh
### BEGIN INIT INFO
# Provides:          teamspeak
# Required-Start:    networking
# Required-Stop:     \$remote_fs \$syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: TeamSpeak Server Daemon
# Description:       Controls TeamSpeak Server Daemon
### END INIT INFO

sudo -H -u ts bash ${INSTALLDIR}/ts/ts3server_startscript.sh \$1
EOF
chmod +x /etc/init.d/ts

Log "Registering startup script to defaults"
update-rc.d ts defaults > /dev/null

LogGreen "Done! Start the server with:"
LogBlue "/etc/init.d/ts start"