#!/bin/bash

if [ -z "${FTP_MYSQL_DATABASE}" ] || [ -z "${FTP_MYSQL_USERNAME}" ] || [ -z "${FTP_MYSQL_PASSWORD}" ]; then
	LogRed "FTP not configured. Missing MySQL details (${PKG}/ftp/tmp/mysql)"
	exit
fi